controller_manager:
    ros__parameters:
        update_rate: 500
        # Publish joint_states
        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster
            publish_rate: 1000

        arm_position_controller:
            type: joint_trajectory_controller/JointTrajectoryController


# left leg Controllers ---------------------------------------
arm_position_controller:
    ros__parameters:
        joints:
            - Joint1
            - Joint2
            - Joint3
            - Joint4
            - Joint5
            - Joint6
        command_interfaces: 
            - position
        state_interfaces:
            - position
            - velocity
            - acceleration
        open_loop_control: true
        allow_integration_in_goal_trajectories: true
        gains:
            Joint1:
                p: 500
                d: 1
                i: 1
                i_clamp: 1
            Joint2:
                p: 500
                d: 1
                i: 1
                i_clamp: 1
            Joint3:
                p: 500
                d: 1
                i: 1
                i_clamp: 1
            Joint4:
                p: 500
                d: 1
                i: 1
                i_clamp: 1
            Joint5:
                p: 500
                d: 1
                i: 1
                i_clamp: 1
            Joint6:
                p: 500
                d: 1
                i: 1
                i_clamp: 1
