controller_manager:
    ros__parameters:
        update_rate: 500
        # Publish all joint states -----------------------------------
        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster
        FL_hip_controller:
            type: robot_joint_controller/RobotJointController
        FL_thigh_controller:
            type: robot_joint_controller/RobotJointController
        FL_calf_controller:
            type: robot_joint_controller/RobotJointController
        FR_hip_controller:
            type: robot_joint_controller/RobotJointController
        FR_thigh_controller:
            type: robot_joint_controller/RobotJointController
        FR_calf_controller:
           type: robot_joint_controller/RobotJointController
        RL_hip_controller:
           type: robot_joint_controller/RobotJointController
        RL_thigh_controller:
           type: robot_joint_controller/RobotJointController
        RL_calf_controller:
           type: robot_joint_controller/RobotJointController
        RR_hip_controller:
            type: robot_joint_controller/RobotJointController
        RR_thigh_controller:
           type: robot_joint_controller/RobotJointController
        RR_calf_controller:
            type: robot_joint_controller/RobotJointController

# left leg Controllers ---------------------------------------
FL_hip_controller:
    ros__parameters:
        joint: FL_hip_joint
        # 为了能读到xacro内容来获取关节标签内容(主要是关节的限位限速)
        robot_description: /home/wl/Documents/simulation_all_ros2/src/robot_description/mz/xacro/robot_system.xacro
FL_thigh_controller:
    ros__parameters:
        joint: FL_thigh_joint
        robot_description: /home/wl/Documents/simulation_all_ros2/src/robot_description/mz/xacro/robot_system.xacro
FL_calf_controller:
    ros__parameters:
        joint: FL_calf_joint
        robot_description: /home/wl/Documents/simulation_all_ros2/src/robot_description/mz/xacro/robot_system.xacro
FR_hip_controller:
    ros__parameters:
        joint: FR_hip_joint
        robot_description: /home/wl/Documents/simulation_all_ros2/src/robot_description/mz/xacro/robot_system.xacro
FR_thigh_controller:
    ros__parameters:
        joint: FR_thigh_joint
        robot_description: /home/wl/Documents/simulation_all_ros2/src/robot_description/mz/xacro/robot_system.xacro
# right leg Controllers ---------------------------------------
FR_calf_controller:
    ros__parameters:
        joint: FR_calf_joint
        robot_description: /home/wl/Documents/simulation_all_ros2/src/robot_description/mz/xacro/robot_system.xacro
RL_hip_controller:
    ros__parameters:
        joint: RL_hip_joint
        robot_description: /home/wl/Documents/simulation_all_ros2/src/robot_description/mz/xacro/robot_system.xacro
RL_thigh_controller:
    ros__parameters:
        joint: RL_thigh_joint
        robot_description: /home/wl/Documents/simulation_all_ros2/src/robot_description/mz/xacro/robot_system.xacro
RL_calf_controller:
    ros__parameters:
        joint: RL_calf_joint
        robot_description: /home/wl/Documents/simulation_all_ros2/src/robot_description/mz/xacro/robot_system.xacro
RR_hip_controller:
    ros__parameters:
        joint: RR_hip_joint
        robot_description: /home/wl/Documents/simulation_all_ros2/src/robot_description/mz/xacro/robot_system.xacro
RR_thigh_controller:
    ros__parameters:
        joint: RR_thigh_joint
        robot_description: /home/wl/Documents/simulation_all_ros2/src/robot_description/mz/xacro/robot_system.xacro
RR_calf_controller:
    ros__parameters:
        joint: RR_calf_joint
        robot_description: /home/wl/Documents/simulation_all_ros2/src/robot_description/mz/xacro/robot_system.xacro